#!/bin/bash

# -----------------------------------------------------------------------------
# SIP-EPHEMERAL-START
# -----------------------------------------------------------------------------
#
# Create and run the ephemeral SIP containers. The number of containers
# depends on the CORES count (one SIP instance per 8 cores) but it can not be
# more than LIMIT. The cores count is token into account if it's greater than
# RESERVED.
#
# For example, if there are 24 cores and 8 of them are reserved, the remaining
# 16 cores are used for the SIP instances. So there will be 2 active SIP
# instances ( 16/8 = 2 )
#
# -----------------------------------------------------------------------------

# The maximum number of the SIP instances. This is related with the ALSA
# loopback and v4l2loopback count. See /etc/modprobe.d/alsa-loop.conf and
# /etc/modprobe.d/v4l2loopback.conf on the host.
LIMIT=4

# The reserved cores count. The number of the cores which is not token into
# account to calculate the number of Jibri instances.
RESERVED=0

# The number of cores per each SIP instance.
CPI=8

# The total cores
CORES=$(nproc --all)

# The available cores count
(( N = LIMIT * CPI ))
(( M = CORES - RESERVED ))
[[ $N -gt $M ]] && N=$M

for c in $(seq $CPI $CPI $N); do
    (( ID = c / $CPI ))

    lxc-stop -k -n eb-sip-$ID 2>/dev/null
    lxc-wait -n eb-sip-$ID -s STOPPED 2>/dev/null
    rm -rf /var/lib/lxc/eb-sip-$ID
    sleep 2

    (( VID0 = ID * 2 ))
    (( VID1 = VID0 + 1 ))

    lxc-copy -n eb-sip-template -N eb-sip-$ID -e \
        -m bind=/dev/video$VID0:/dev/video0:rw \
        -m bind=/dev/video$VID1:/dev/video1:rw
done
